### ISSUE TITLE
bundleDependancies should include extra packages on NPM 2

### ISSUE THREAD

**Issue by ilyavolodin** [gajus/bundle-dependencies#3]
There's a known issue about having same sub-dependencies under both `devDependancies` and `dependancies` (for more information see here: https://github.com/npm/npm/issues/7887). I think the right solution in this case is to have those cases be included in `bundleDependancies` explicitly. If you look at https://github.com/eslint/eslint/issues/5687 it might make it a bit clearer what I'm talking about. Let me know if you need more information.

**Comment by gajus** [comment]
@ilyavolodin How is this different from the current behaviour?

**Comment by ilyavolodin** [comment]
I think (correct me if I'm wrong), current behavior only checks top level dependencies. The bug with NPM 2 is that if you have top level dependency that has a direct dependency on the same package that you use in devDependencies, the second-level dependency will not be included in bundleDependencies (can I use word "dependency" even more in that sentence?!). So the change would be to do recursive check for all of the package in `dependencies` and compare them to `devDependencies`, if one of the transient dependencies is found in both, it should be included into `bundleDependencies` explicitly.

**Comment by gajus** [comment]
That will not work. Two packages might have dependency on different package versions.

There is no way to fix this in NPM2 as far as I can tell.

**Comment by gajus** [comment]
@ilyavolodin took me 5 months to realise that this is irrelevant (and @nzakas [comment](https://github.com/eslint/eslint/issues/5013#issuecomment-244147696)).

The bundle is produced on NPM v3 (presumably the CI or whatever is publishing the bundle is running NPM v3+). It doesn't matter if you install it on NPM v1, v2 or v3.

Can I close this or did I miss something?
